version: "3.7"

volumes:
  peer0.supplychain.example.com:

networks:
  bpn_network:
    name: bpn_network
    external: true

services:
  couchdb1:
    container_name: couchdb1
    extends:
      file: docker-compose-base.yaml
      service: couchdb-base
    ports:
      - "6984:5984"
    networks:
      - bpn_network

  peer0.supplychain.example.com:
    container_name: peer0.supplychain.example.com
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    environment:
      # Peer specific variables
      - CORE_PEER_ID=peer0.supplychain.example.com
      - CORE_PEER_ADDRESS=peer0.supplychain.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.supplychain.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.supplychain.example.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.supplychain.example.com:9051
      - CORE_PEER_LOCALMSPID=SupplyChainMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.supplychain.example.com:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0supplychain"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    depends_on:
      - couchdb1
    volumes:
      - ../../organizations/peerOrganizations/supplychain.example.com/peers/peer0.supplychain.example.com:/etc/hyperledger/fabric
      - ../../organizations/peerOrganizations/supplychain.example.com/peers/peer0.supplychain.example.com/msp:/etc/hyperledger/fabric/msp
      - ../../organizations/peerOrganizations/supplychain.example.com/peers/peer0.supplychain.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.supplychain.example.com:/var/hyperledger/production
    command: peer node start
    ports:
      - 9051:9051
      - 9445:9445
    networks:
      - bpn_network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5.5
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/config
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ../../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../../config:/etc/hyperledger/config
    depends_on:
      - peer0.supplychain.example.com
    networks:
      - bpn_network
